// ...existing code...
<ul className="navbar-nav">
    // ...existing nav items...
    <li className="nav-item">
        <Link className="nav-link" to="/kitchen">Kitchen</Link>
    </li>
</ul>
// ...existing code...
